version: '3.8'
services:
  back:
    container_name: back 
    depends_on:
      - mysql_db
    ports:
      - 80:3000
    build: ./
    restart: unless-stopped
    # combine below two together makes `-it` option when you use `docker exec -it`
    stdin_open: true # `-i`
    tty: true # `-t`
    env_file:
        - config/.env

    networks:
      - mysql_db

  mysql_db:
    # image: mysql
    container_name: back-db 
    build: ./mysql
    restart: unless-stopped
    env_file:
      - config/.env
    ports:
      - 3306:3306
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    environment:
        - LC_ALL=C.UTF-8
    # command:
      #- --character-set-server=utf8mb4
      #- --collation-server=utf8mb4_unicode_ci
    volumes:
      - bee-volume:/var/lib/mysql  # -v option
    networks:
      - mysql_db
volumes:
    bee-volume:
      external: true
networks:
    mysql_db:
