version: '3.8'
services:
  back:
    container_name: back 
    ports:
      - 80:3000
    build: ./
    restart: unless-stopped
    env_file:
      - config/.env

    # combine below two together makes `-it` option when you use `docker exec -it`
    stdin_open: true # `-i`
    tty: true # `-t`

